name: copernicus-env-uls
channels:
  - conda-forge
  - anaconda
  - conda-forge/label/gcc7
  - flynn
  - bioconda
  - pyviz
dependencies:
  - python
  - basemap
  - basemap-data-hires
  - bokeh
  - cartopy
  - dask-core
  - folium
  - ftputil
  - geocoder
  - geoviews
  - geoviews-core
  - holoviz
  - imageio
  - ipyleaflet
  - ipywidgets
  - iris
  - libnetcdf>=4.6.1
  - matplotlib
  - ncftp
  - nco>=4.7.7
  - nc-time-axis
  - netcdf4>=1.4.2
  - netcdf-fortran>=4.4.4
  - numba
  - numpy
  - owslib
  - pandas
  - pathlib2
  - pip
  - pivottablejs
  - qgrid
  - requests 
  - scikit-image
  - scipy
  - seaborn
  - thriftpy
  - xarray
  - xarray-extras
  - xrviz
  - pip:
    - jupyter-datatables
    - motuclient>=1.8.1
    - cdo>=1.4.0
    - jupyter-contrib-nbextensions
